# Generated by Django 5.2.2 on 2025-06-30 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='chairperson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='co_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_supervised_students', to='fses.lecturer'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='TEMP001', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
