# Generated by Django 5.2.2 on 2025-06-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='TEMP001', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
