# Generated by Django 5.2.2 on 2025-06-29 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fses', '0002_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='co_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_supervised_students', to='fses.lecturer'),
        ),
    ]
