# Generated by Django 5.2.2 on 2025-06-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fses', '0003_student_co_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='chairperson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
